<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260725223400 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Creates activity and transaction tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, goal_amount NUMERIC(12, 2) NOT NULL, raised_amount NUMERIC(12, 2) NOT NULL, status VARCHAR(20) NOT NULL, category VARCHAR(50) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN activity.goal_amount IS \'(DC2Type:decimal)\'');
        $this->addSql('COMMENT ON COLUMN activity.raised_amount IS \'(DC2Type:decimal)\'');

        $this->addSql('CREATE TABLE transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, activity_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, amount NUMERIC(12, 2) NOT NULL, type VARCHAR(20) NOT NULL, description VARCHAR(255) NOT NULL, category VARCHAR(100) DEFAULT NULL, payment_method VARCHAR(50) DEFAULT NULL, transaction_date DATE NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN transaction.amount IS \'(DC2Type:decimal)\'');
        $this->addSql('COMMENT ON COLUMN transaction.created_at IS \'(DC2Type:datetime)\'');
        $this->addSql('CREATE INDEX IDX_4A29754481C06096 ON transaction (activity_id)');
        $this->addSql('CREATE INDEX IDX_4A297544B03A8386 ON transaction (created_by_id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_4A29754481C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_4A297544B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_4A29754481C06096');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_4A297544B03A8386');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE activity');
    }
}
